ranks:
  example: A

passwords:
  example: password

warns:
  example: 1

mutes:
  example: 1

nicknames:
  example: example

rankprices:
  enabled: true
  A: 1000
  B: 5000
  C: 10000

warps:
  enabled: true