main: me.koenn.kp.Main
name: HexicPrison
description: Hexic Prison Plugin
author: Koenn
version: 1.0

commands:
  mute:
    usage: /mute <player> <time> <s,m,h,d}>
    description: Mutes or unmutes a player.
  setprisonrank:
    usage: CONSOLE ONLY
    description: Sets the prison rank prefix of a player.
  nick:
    usage: /nick [player] <nickname>
    description: Sets a player's nickname.
  chat:
    usage: /chat
    description: Change chat mode (Server or Global).
    aliases: /ch
  relog:
    usage: /relog <player>
    description: Forces a player to relog.
  gotoserver:
    usage: /gotoserver <player> <server>
    description: Connects a player to a server.
  help:
    alias: /settings
    usage: /help
    description: Opens settings menu.
  hub:
    usage: /hub
    description: Teleports you to the Hub.
  adminmode:
    usage: /adminmode <password>
    description: Log in to adminmode.
  adminregister:
    usage: /adminregister <password>
    description: Register as an admin (Op required)
  blockcmd:
    usage: CONSOLE ONLY
    description: Blocks all commands for a player.
  history:
    usage: /history <player>
    description: See the history of the player.
  warn:
    usage: /warn <player> <reason>
    description: Give a player a warning.
  rankup:
    usage: /rankup
    description: Rankup.
  setrank:
    usage: /setrank <player> <rank>
    description: Set a player's rank.
  emoney:
    usage: /emoney <add/remove/set> <player> <amount>
    description: General economy command.
  bal:
    aliases: /balance
    usage: /bal [player]
    desctiption: Check your balance
  pay:
    usage: /pay <player> <amount>
    description: Pay a player.
  warp:
    usage: /warp (warp)
    description: Warp to places
  setwarp:
    usage: /setwarp <name> <item>
    desctiption: Set a warp
  unrent:
    usage: /unrent
    desctiption: Unrent your cell.
  kit:
    usage: /kit
    description: Get a kit.

permissions:
  hexic.Dev:
    description: All hexic developer/owner only stuff.
    default: op
  hexic.Helper:
    description: For all our awsome helpers.
    default: op
  hexic.Nick:
    description: Allows you to set your nickname.
    default: op