main: me.koenn.kp.Main
name: Hexic Prison
description: Hexic Prison Plugin
author: Koenn
version: 1.0

commands:
  mute:
    usage: /mute <player>
    description: Mutes or unmutes a player.
  setprisonrank:
    usage: CONSOLE ONLY
    description: Sets the prison rank prefix of a player.
  nick:
    usage: /nick [player] <nickname>
    description: Sets a player's nickname.
  chat:
    usage: /chat
    description: Change chat mode (Server or Global).
  relog:
    usage: /relog <player>
    description: Forces a player to relog.
  gotoserver:
    usage: /gotoserver <player> <server>
    description: Connects a player to a server.
  help:
    alias: /settings
    usage: /help
    description: Opens settings menu.
  hub:
    usage: /hub
    description: Teleports you to the Hub.
  adminmode:
    usage: /adminmode <password>
    description: Log in to adminmode.
  adminregister:
    usage: /adminregister <password>
    description: Register as an admin (Op required)

permissions:
  hexic.Dev:
    description: All hexic developer/owner only stuff.
    default: op
  hexic.Helper:
    description: For all our awsome helpers.
    default: op
  hexic.Nick:
    description: Allows you to set your nickname.
    default: op